
stages:
  - build

cache:
  key: "$CI_BUILD_NAME"
  untracked: true

compile:windows:
  stage: build
  tags:
    - msbuild
  before_script:
    - git submodule update --init
  script:
    - ruby scripts\ci-compile.rb windows
  artifacts:
    paths:
      - compile-artifacts

compile:darwin:
  stage: build
  tags:
    - darwin
  script:
    - scripts/ci-compile.rb darwin
  artifacts:
    paths:
      - compile-artifacts

      
